env:
  browser: true
  commonjs: true
  es6: true
  node: true
  amd: true
parserOptions:
  ecmaVersion: 8
extends: 'eslint:recommended'
rules:
  no-eval: 2
  indent:
  - off
  - 4
  - SwitchCase: 1
  linebreak-style: 2
  no-undef: 2
  no-unused-vars:
  - 2
  - vars: local
  no-caller: 2
  no-empty: 2
  no-eq-null: 2
  curly:
  - 2
  - all
  operator-linebreak:
  - 2
  - after
  quotes:
  - 2
  - single
  no-multi-str: 2
  no-mixed-spaces-and-tabs: 2
  no-trailing-spaces: 2
  space-unary-ops:
  - 2
  - nonwords: false
    overrides: {}
  brace-style:
  - 2
  - 1tbs
  - allowSingleLine: true
  keyword-spacing:
  - 2
  - {}
  space-infix-ops: 2
  space-before-blocks:
  - 2
  - always
  array-bracket-spacing:
  - 2
  - never
  space-in-parens:
  - 2
  - never
  no-multiple-empty-lines: 2
  no-with: 2
  space-before-function-paren:
  - 2
  - anonymous: ignore
    named: never
  no-spaced-func: 2
  key-spacing:
  - 2
  - beforeColon: false
    afterColon: true
  dot-notation: 2
  semi:
  - 2
  - always
  comma-dangle:
    - off
    - arrays: never
      objects: never
      imports: never
      exports: never
      functions: ignore

